
server:
  port: 8001
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/issue
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      javax:
        persistence:
          validation:
            mode: none